language:
  java

jdk:
  - oraclejdk8

node_js:
  - "10"

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]
    then
      echo 'Sending jar file'
      curl -X POST http://ec2-3-14-226-139.us-east-2.compute.amazonaws.com:9002/deploy -F 'jar=@/home/travis/build/skosinskiy/dan-it-final-project/target/final-project-0.0.1-SNAPSHOT.jar' -F 'branch=master'
    fi

addons:
  sonarcloud:
    organization: "skosinskiy-github"
    token:
      secure: ${SONAR_TOKEN}