language:
  java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - frontend/admin_panel/node_modules/
    - frontend/mobile/node_modules/
    - frontend/screen/node_modules/

script:
  - mvn clean package
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - bash <(curl -s http://ec2-3-14-226-139.us-east-2.compute.amazonaws.com:9002/deploy?branch=master)

addons:
  sonarcloud:
    organization: "skosinskiy-github"
    token:
      secure: ${SONAR_TOKEN}