spring:
  datasource:
    url:
      jdbc:h2:mem:app;DB_CLOSE_ON_EXIT=FALSE
    username:
      sa

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials
server:
  ssl:
    enabled: false