spring:
  jackson:
    mapper:
      default-view-inclusion: true
  datasource:
    url:
      jdbc:mysql://awsdb.cdsununkklcc.us-east-2.rds.amazonaws.com:3306/rion_up?useSSL=false&serverTimezone=UTC
    username:
      rionupuser
    password:
      Yf8Ionc%1
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 725984848177-a2j2u673nn1gb912mku0k9qe762ikgl6.apps.googleusercontent.com
            client-secret: JCLQB32uWdgAN6FBepbqqQLe
          facebook:
            client-id: 410043406474015
            client-secret: 4d020bd87e29aab5fa5a68ff827faee2
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      noreplyrionup@gmail.com
    password:
      crmcsdjqkkvansiy
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true
  servlet:
    multipart:
      max-file-size:
        10MB
server:
  port:
    9000

react:
  server:
    port:
      9000
    host:
      ec2-3-14-226-139.us-east-2.compute.amazonaws.com
aws:
  s3:
    credentials:
      path:
        /home/ubuntu/aws/s3/credentials