spring:
  profiles:
    active:
      dev
  datasource:
    url:
      jdbc:h2:mem:app;DB_CLOSE_ON_EXIT=FALSE
    username:
      sa
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      noreplyrionup@gmail.com
    password:
      crmcsdjqkkvansiy
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true
server:
  port:
    9000

react:
  server:
    port:
      3000
    host:
      localhost

aws:
  s3:
    credentials:
      path:
        src/main/resources/aws/s3/credentials