spring:
  datasource:
    url:
      jdbc:h2:mem:app;DB_CLOSE_ON_EXIT=FALSE
    username:
      sa
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      noreplyrionup@gmail.com
    password:
      crmcsdjqkkvansiy
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true
server:
  port:
    9000